### ISSUE TITLE
Problem when connecting

### ISSUE THREAD

**Issue by Nexuzzzz** [iIIusi0n/Simple-IRC-Botnet#2]
1. Bot tries to connect (Works fine)
2. Bot logs in with nickname and username (Works fine)
3. Connection gets resetted and bot reconnects?

I took a look at Wireshark and i got a lot of RST packets, any idea's on what could've gone wrong?

**Comment by iIIusi0n** [comment]
You should set the correct IRC auth message. If you need stress testing tool, plz check wyvern-stress-tester :)
